name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  actions: read
  contents: write

env:
  PYTHON_VERSION: "3.13"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed for docs to discover gh-pages branch
          fetch-depth: 0
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-groups
      - name: Build package
        run: uv build

      - name: Ruff
        run: uv run ruff check .
      - name: Black
        run: uv run ruff format --check .
      - name: Run library tests
        run: uv run python -m ziglang build test
      - name: Pytest
        run: uv run pytest
      - name: Check generated stubs
        run: uv run python -m ziglang build --build-file pytest.build.zig generate-stubs -Dcheck-stubs=true
      - name: Zig Docs Build
        run: uv run python -m ziglang build docs
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs Deploy
          git config --global user.email docs@dummy.bot.com
      - name: MKDocs Build
        run: uv run mike deploy develop --push
        if: ${{ github.ref == 'refs/heads/develop' }}
