name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  actions: read
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed for docs to discover gh-pages branch
          fetch-depth: 0

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment and install dependencies
        run: |
          source .venv/bin/activate
          uv sync --active --all-groups

      - name: Build package
        run: |
          source .venv/bin/activate
          uv build

      - name: Ruff
        run: |
          source .venv/bin/activate
          uv run --active ruff check .
      - name: Black
        run: |
          source .venv/bin/activate
          uv run --active ruff format --check .
      - name: Run library tests
        run: |
          source .venv/bin/activate
          uv run --active python -m ziglang build test
      - name: Pytest
        run: |
          source .venv/bin/activate
          uv run --active pytest
      # - name: Check generated stubs
      #   run: |
      #     source .venv/bin/activate
      #     uv run --active -m ziglang build --build-file pytest.build.zig generate-stubs -Dcheck-stubs=true
      - name: Zig Docs Build
        run: |
          source .venv/bin/activate
          uv run --active -m ziglang build docs
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13' }}

      - name: Setup doc deploy
        run: |
          git config --global user.name Docs Deploy
          git config --global user.email docs@dummy.bot.com
        if: ${{ github.ref == 'refs/heads/develop' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13' }}

      - name: MKDocs Build
        run: |
          source .venv/bin/activate
          uv run --active mike deploy develop --push
        if: ${{ github.ref == 'refs/heads/develop' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13' }}
