name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  actions: read
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Configure use-uv
        run: pdm config use_uv true

      - name: Install dependencies (Dev)
        run: pdm install -d

      - name: Build package
        run: pdm build

      - name: Ruff
        run: pdm run ruff check .

      - name: Ruff Format
        run: pdm run ruff format --check .

  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Configure use-uv
        run: pdm config use_uv true

      - name: Install dependencies (Dev)
        run: pdm install -d

      - name: Run build check
        run: uv run zig build check

  check-abi3:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Configure use-uv
        run: pdm config use_uv true

      - name: Install dependencies (Dev)
        run: pdm install -d

      - name: Run build check
        run: uv run zig build check -Dabi3=true

  build:
    needs: [lint, check]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Configure use-uv
        run: pdm config use_uv true

      - name: Install dependencies (Dev)
        run: pdm install -d

      - name: Run build tests
        run: pdm run zig build test
      # - name: Pytest
      #   run: pdm run pytest
      # - name: Check generated stubs
      #   run: pdm run python -m ziglang build --build-file pytest.build.zig generate-stubs -Dcheck-stubs=true

  build-abi3:
    needs: [lint, check-abi3]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Configure use-uv
        run: pdm config use_uv true

      - name: Install dependencies (Dev)
        run: pdm install -d

      - name: Run build tests (abi3)
        run: pdm run zig build test -Dabi3=true

  docs:
    runs-on: ubuntu-latest
    needs: [lint, build, build-abi3]
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed for docs to discover gh-pages branch
          fetch-depth: 0

      - uses: mlugg/setup-zig@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Configure use-uv
        run: pdm config use_uv true

      - name: Install dependencies (Dev)
        run: pdm install -d

      - name: Zig Docs Build
        run: pdm run zig build docs

      - name: Setup doc deploy
        run: |
          git config --global user.name Docs Deploy
          git config --global user.email docs@dummy.bot.com

      - name: MKDocs Build
        run: pdm run mike deploy develop --push
